// src/components/base/HeaderUserMenuItem.svelte
<style lang="scss" scoped>
  @import '../../styles/variables.scss';
  .user-menu-item {
    color: $gray9;
    padding: 0.75rem 1rem;
    line-height: 1.5;
    font-weight: 500;
    cursor: pointer;
    &:hover {
      background: $gray0;
    }
  }

  .wrapper-link > a {
    display: block;
    color: inherit;
    text-decoration: none;
  }
</style>

<script lang="ts">
  export let to: string = '';
</script>

{#if to}
  <div class="wrapper-link">
    <a href="{to}">
      <div class="user-menu-item" on:click>
        <slot>
          <!-- option fallback -->
        </slot>
      </div>
    </a>
  </div>
{:else}
  <div class="user-menu-item" on:click>
    <slot>
      <!-- option fallback -->
    </slot>
  </div>
{/if}

// src/components/main/HeaderUserMenuItem.tsx
import React from 'react';
import Link from 'next/link';
import styled from 'styled-components';
import palette from '~/libs/styles/palette';

const HeaderUserMenuItemBlock = styled.div`
  color: ${palette.gray9};
  padding: 0.75rem 1rem;
  line-height: 1.5;
  font-weight: 500;
  cursor: pointer;
  &:hover {
    background: ${palette.gray0};
  }
`;

const WrapperLink = styled.a`
  display: block;
  color: inherit;
  text-decoration: none;
`;

interface HeaderUserMenuItemProps {
  children: React.ReactNode;
  to?: string;
  onClick?: () => void;
}
function HeaderUserMenuItem({
  children,
  to,
  onClick,
}: HeaderUserMenuItemProps) {
  const jsx = (
    <HeaderUserMenuItemBlock onClick={onClick}>
      {children}
    </HeaderUserMenuItemBlock>
  );
  return to ? (
    <Link href={to}>
      <WrapperLink style={{ display: 'block' }}>{jsx}</WrapperLink>
    </Link>
  ) : (
    jsx
  );
}

export default HeaderUserMenuItem;
