// src/components/main/MainResponsive.svelte
<style lang="scss">
  @import '../../styles/variables.scss';

  .responsive {
    width: 1728px;
    margin-left: auto;
    margin-right: auto;
    @media (max-width: $xxlarge) {
      width: 1376px;
    }

    @media (max-width: $xlarge) {
      width: 1280px;
    }

    @media (max-width: 1312px) {
      width: 912px;
    }

    @media (max-width: 944px) {
      width: calc(100% - 2rem);
    }

    @media (max-width: $small) {
      width: calc(100% - 2rem);
    }
  }
</style>

<div class="responsive">
  <slot>
    <!-- option fallback -->
  </slot>
</div>

// src/components/main/MainResponsive.tsx
import React from 'react';
import styled from 'styled-components';
import { mediaQuery } from '~/libs/styles/media';

export type MainResponsiveProps = {
  className?: string;
  children: React.ReactNode;
};

function MainResponsive({ className, children }: MainResponsiveProps) {
  return <Block className={className}>{children}</Block>;
}

const Block = styled.div`
  width: 1728px;
  margin-left: auto;
  margin-right: auto;
  ${mediaQuery(1919)} {
    width: 1376px;
  }
  ${mediaQuery(1440)} {
    width: 1280px;
  }
  ${mediaQuery(1312)} {
    width: 912px;
  }
  ${mediaQuery(944)} {
    width: calc(100% - 2rem);
  }
  ${mediaQuery(767)} {
    width: calc(100% - 2rem);
  }
`;

export default MainResponsive;
