// src/components/write/PublishScreenTemplate.tsx
import React, { useEffect, useState } from 'react';
import styled, { css } from 'styled-components';
import media from '~/libs/styles/media';
import palette from '~/libs/styles/palette';
import transitions from '~/libs/styles/transitions';
import zIndexes from '~/libs/styles/zIndexes';

const PublishScreenTemplateBlock = styled.div<{ visible: boolean }>`
  display: flex;
  justify-content: center;
  align-items: center;
  position: fixed;
  @media (max-width: 1024px) and (orientation: landscape) {
    align-items: flex-start;
    padding-top: 2rem;
    padding-bottom: 2rem;
    overflow: auto;
  }
  ${media.custom(767)} {
    align-items: flex-start;
    padding-top: 2rem;
    padding-bottom: 2rem;
    overflow: auto;
    padding-left: 1rem;
    padding-right: 1rem;
  }
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background: ${palette.gray0};
  z-index: ${zIndexes.PublishScreen};
  animation: ${transitions.slideUp} 0.25s forwards ease-in;
  ${(props) =>
    props.visible
      ? css`
          animation: ${transitions.slideUp} 0.25s forwards ease-in;
        `
      : css`
          animation: ${transitions.slideDown} 0.125s forwards ease-out;
        `}
`;

const Wrapper = styled.div`
  width: 768px;
  display: flex;
  ${media.medium} {
    width: 704px;
  }
  ${media.custom(767)} {
    flex-direction: column;
  }
`;

const Pane = styled.div`
  flex: 1;
  min-width: 0;
`;

const RightPane = styled(Pane)`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
`;

const Separator = styled.div`
  width: 1px;
  min-height: 425px;
  background: ${palette.gray2};
  margin-left: 2rem;
  margin-right: 2rem;
  ${media.custom(767)} {
    display: none;
  }
`;

interface PublishScreenTemplateProps {
  visible: boolean;
  left: React.ReactNode;
  right: React.ReactNode;
}

function PublishScreenTemplate({
  visible,
  left,
  right,
}: PublishScreenTemplateProps) {
  const [animate, setAnimate] = useState(false);

  useEffect(() => {
    let timeoutId: null | ReturnType<typeof setTimeout> = null;
    if (visible) {
      setAnimate(true);
    } else if (!visible && animate) {
      timeoutId = setTimeout(() => {
        setAnimate(false);
      }, 125);
    }
    return () => {
      if (timeoutId) {
        clearTimeout(timeoutId);
      }
    };
  }, [visible, animate]);

  if (!visible && !animate) return null;

  return (
    <PublishScreenTemplateBlock visible={visible}>
      <Wrapper>
        <Pane>{left}</Pane>
        <Separator />
        <RightPane>{right}</RightPane>
      </Wrapper>
      {/* <HideScroll /> */}
    </PublishScreenTemplateBlock>
  );
}

export default PublishScreenTemplate;

// src/components/write/PublishScreenTemplate.svelte
<style lang="scss" scoped>
  @import '../../styles/variables.scss';

  .publish-screen-template {
    display: flex;
    justify-content: center;
    align-items: center;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: $gray0;
    z-index: 15;
    // animation: slideUp 0.25s forwards ease-in;
    @media (max-width: 1024px) and (orientation: landscape) {
      align-items: flex-start;
      padding-top: 2rem;
      padding-bottom: 2rem;
      overflow: auto;
    }

    .wrapper {
      width: 768px;
      display: flex;

      .left-pane {
        flex: 1;
        min-width: 0;
      }

      .right-pane {
        flex: 1;
        min-width: 0;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
      }

      .separator {
        width: 1px;
        min-height: 425px;
        background: $gray2;
        margin-left: 2rem;
        margin-right: 2rem;
      }
    }
  }

  //   @keyframes slideUp {
  //     0% {
  //       transform: translateY(100%);
  //     }
  //     100% {
  //       transform: translateY(0%);
  //     }
  //   }

  //   @keyframes slideDown {
  //     0% {
  //       transform: translateY(0%);
  //     }
  //     100% {
  //       transform: translateY(100%);
  //     }
  //   }

  //   .up {
  //     animation: slideUp 0.25s forwards ease-in;
  //   }

  //   .down {
  //     animation: slideDown 0.125s forwards ease-out;
  //   }
</style>

<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import { slide } from 'svelte/transition';
  import HideScroll from '../common/HideScroll.svelte';

  export let visible = false;

  let animate = false;
  let timeoutId: number | null = null;

  onMount(() => {
    if (visible) {
      animate = true;
    } else if (!visible && animate) {
      timeoutId = setTimeout(() => {
        animate = false;
      }, 100);
    }
    return {
      if(timeoutId) {
        clearTimeout(timeoutId);
      },
    };
  });
</script>

{#if !visible && !animate}
  <div></div>
{:else}
  <div class="publish-screen-template" in:slide="{{ duration: 125 }}">
    <div class="wrapper">
      <div class="left-pane">??</div>
      <div class="separator"></div>
      <div class="right-pane">??</div>
    </div>
    <HideScroll />
  </div>
{/if}
