// src/components/write/TitleTextarea.tsx
import TextareaAutosize from 'react-textarea-autosize';
import styled, { css } from 'styled-components';
import { mediaQuery } from '~/libs/styles/media';
import palette from '~/libs/styles/palette';

const style = css`
  display: block;
  padding: 0;
  font-size: 2.75rem;
  ${mediaQuery(767)} {
    font-size: 1.8rem;
  }
  width: 100%;
  resize: none;
  line-height: 1.5;
  outline: none;
  border: none;
  font-weight: bold;
  color: ${palette.gray9};
  &::placeholder {
    color: ${palette.gray5};
  }
`;

const TitleTextarea = styled(TextareaAutosize)`
  ${style}
`;

export default TitleTextarea;

// src/components/write/TitleTextarea.svelte
<style lang="scss" scoped>
  @import '../../styles/variables.scss';

  textarea {
    display: block;
    padding: 0;
    font-size: 2.75rem;
    width: 100%;
    resize: none;
    line-height: 1.5;
    outline: none;
    border: none;
    font-weight: bold;
    color: $gray9;
    &::placeholder {
      color: $gray5;
    }
  }
</style>

<script>
  export let title = '';
</script>

<textarea value="{title}" on:keypress placeholder="제목을 입력하세요" rows="1" autocomplete="off"></textarea>
