// src/components/write/WriteFooter.tsx
import React from 'react';
import styled from 'styled-components';
import { MdArrowBack } from 'react-icons/md';
import Button from '../common/Button';
import media from '~/libs/styles/media';

interface WriteFooterProps {
  onTempSave: (notify?: boolean) => void;
  onPublish: () => void;
  onGoBack: () => void;
  edit: boolean;
}
function WriteFooter({
  onTempSave,
  onPublish,
  onGoBack,
  edit,
}: WriteFooterProps) {
  return (
    <WriteFooterBlock>
      <BackButton onClick={onGoBack}>
        <MdArrowBack />
        <span>나가기</span>
      </BackButton>
      <Group>
        <StyledButton inline color="lightGray" onClick={() => onTempSave()}>
          임시저장
        </StyledButton>
        <StyledButton inline color="teal" onClick={onPublish}>
          {edit ? '수정하기' : '출간하기'}
        </StyledButton>
      </Group>
    </WriteFooterBlock>
  );
}

export default WriteFooter;

const WriteFooterBlock = styled.div`
  padding-left: 1rem;
  padding-right: 1rem;
  height: 4rem;
  width: 100%;
  box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.1);
  background: rgba(255, 255, 255, 0.85);
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const Group = styled.div`
  justify-content: flex-end;
  align-items: center;
`;

const StyledButton = styled(Button)`
  height: 2.5rem;
  font-size: 1.125rem;
  & + & {
    margin-left: 0.75rem;
  }
`;

const BackButton = styled.button`
  height: 2.5rem;
  padding: 0.5rem 1rem;
  align-items: center;
  background: none;
  border-radius: 4px;
  cursor: pointer;
  border: none;
  display: flex;
  outline: none;
  &:hover,
  &:focus {
    background: rgba(0, 0, 0, 0.05);
  }
  svg {
    font-size: 1.25rem;
    margin-right: 0.5rem;
  }
  span {
    font-size: 1.125rem;
    ${media.xsmall} {
      display: none;
    }
  }
`;

// src/components/write/WriteFooter.svelte
<style lang="scss">
  .write-footer-block {
    padding-left: 1rem;
    padding-right: 1rem;
    height: 4rem;
    width: 100%;
    box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.1);
    background: rgba(255, 255, 255, 0.85);
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .back-btn {
    height: 2.5rem;
    width: 7rem;
    padding: 0.5rem 1rem;
    -webkit-box-align: center;
    align-items: center;
    background: none;
    border-radius: 4px;
    cursor: pointer;
    border: none;
    display: flex;
    left: 0;
    outline: none;
    &:hover,
    &:focus {
      background: rgba(0, 0, 0, 0.05);
    }
    & > .arrowback-icon {
      height: 1.25rem;
      width: 100%;
      margin-right: 0.5rem;
    }
  }

  .group {
    justify-content: flex-end;
    align-items: center;
    & > :global(button) {
      height: 2.5rem;
      font-size: 1.125rem;
      margin-left: 0.75rem;
      margin-top: 0.5rem;
      border-radius: 5px !important;
    }
  }
</style>

<script lang="ts">
  import ArrowBackIcon from 'svelte-icons/md/MdArrowBack.svelte';
  import RoundButton from '../common/RoundButton.svelte';
  import write from '../../store/write';

  export let edit = false;

  const onGoBack = () => {
    history.back();
  };

  const onOpenPublish = () => {
    write.openPublish();
  };
</script>

<div class="write-footer-block">
  <button type="button" class="back-btn" on:click="{onGoBack}">
    <div class="arrowback-icon">
      <ArrowBackIcon />
    </div>
  </button>
  <div class="group">
    <RoundButton inline="{true}" color="gray">임시저장</RoundButton>
    <RoundButton inline="{true}" color="teal" on:click="{onOpenPublish}">{edit ? '수정하기' : '출간하기'}</RoundButton>
  </div>
</div>
