// src/containers/write/ActiveEditor.svelte
<script lang="ts">
  import EditorPanes from '../../components/write/EditorPanes.svelte';
  import MarkdownEditorContainer from './MarkdownEditorContainer.svelte';
  import MarkdownPreviewContainer from './MarkdownPreviewContainer.svelte';
</script>

<EditorPanes>
  <div slot="left">
    <MarkdownEditorContainer />
  </div>
  <div slot="right">
    <MarkdownPreviewContainer />
  </div>
</EditorPanes>

// src/containers/write/ActiveEditor.tsx
import React from 'react';
import EditorPanes from '~/components/write/EditorPanes';
import MarkdownEditorContainer from './MarkdownEditorContainer';
import MarkdownPreviewContainer from './MarkdownPreviewContainer';

interface ActiveEditorProps {
  isServer: boolean;
}
function ActiveEditor({ isServer }: ActiveEditorProps) {
  return (
    <>
      <EditorPanes
        left={<MarkdownEditorContainer isServer={isServer} />}
        right={<MarkdownPreviewContainer />}
      />
    </>
  );
}

export default ActiveEditor;
