// src/components/common/RoundButton.tsx
import React from 'react';
import styled, { css } from 'styled-components';
import { useRouter } from 'next/router';
import { buttonColorMap } from '~/libs/styles/palette';

type ButtonSize = 'SMALL' | 'DEFAULT' | 'LARGE';

type RoundButtonBlockProps = {
  inline?: boolean;
  color: string;
  size: ButtonSize;
  border: boolean;
};

const RoundButtonBlock = styled.button<RoundButtonBlockProps>`
  ${(props) =>
    props.inline &&
    css`
      & + & {
        margin-left: 1rem;
      }
    `}
  ${(props) =>
    props.size === 'SMALL' &&
    css`
      height: 1.5rem;
      padding-left: 0.75rem;
      padding-right: 0.75rem;
      font-size: 0.875rem;
      border-radius: 0.75rem;
    `};
  ${(props) =>
    props.size === 'DEFAULT' &&
    css`
      height: 2rem;
      padding-left: 1rem;
      padding-right: 1rem;
      font-size: 1rem;
      border-radius: 1rem;
    `};
  ${(props) =>
    props.size === 'LARGE' &&
    css`
      height: 3rem;
      font-size: 1.5rem;
      padding-left: 2rem;
      padding-right: 2rem;
      border-radius: 1.5rem;
    `}
  background: none;
  border: none;
  outline: none;
  font-weight: bold;
  word-break: keep-all;
  background: ${(props) => buttonColorMap[props.color].background};
  color: ${(props) => buttonColorMap[props.color].color};
  &:hover {
    background: ${(props) => buttonColorMap[props.color].hoverBackground};
  }
  ${(props) =>
    props.border &&
    css<RoundButtonBlockProps>`
      background: white;
      border: 1px solid ${(props) => buttonColorMap[props.color].background};
      color: ${(props) => buttonColorMap[props.color].background};
      &:hover {
        background: ${(props) => buttonColorMap[props.color].background};
        color: white;
      }
    `}
  transition: 0.125s all ease-in;
  &:focus {
    box-shadow: 0px 2px 12px #00000030;
  }
  cursor: pointer;
`;

type ButtonProps = React.DetailedHTMLProps<
  React.ButtonHTMLAttributes<HTMLButtonElement>,
  HTMLButtonElement
>;

interface RoundButtonProps extends ButtonProps {
  inline?: boolean;
  to?: string;
  size?: ButtonSize;
  color?: 'teal' | 'gray' | 'darkGray' | 'lightGray';
  border?: boolean;
}

const RoundButton: React.FC<RoundButtonProps> = ({
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  ref,
  to,
  color = 'teal',
  size = 'DEFAULT',
  border = false,
  ...rest
}) => {
  const router = useRouter();
  if (to) {
    return (
      <RoundButtonBlock
        color={color}
        onClick={(e) => {
          e.preventDefault();
          router.push(to);
        }}
        size={size}
        border={border}
        {...rest}
      />
    );
  }
  return (
    <RoundButtonBlock color={color} size={size} border={border} {...rest} />
  );
};

export default RoundButton;

// src/components/common/RoundButton.svelte
<style lang="scss" scoped>
  .round-btn {
    background: none;
    border: none;
    outline: none;
    font-weight: bold;
    word-break: keep-all;
    transition: 0.125s all ease-in;
    &:focus {
      box-shadow: 0px 2px 12px #00000030;
    }
    cursor: pointer;
  }

  :global(.inline-btn + .inline-btn) {
    margin-left: 1rem;
  }

  .border-btn {
    background: white;
    &:hover {
      color: white;
    }
  }

  .default-size {
    height: 2rem;
    padding-left: 1rem;
    padding-right: 1rem;
    font-size: 1rem;
    border-radius: 1rem;
  }

  .small-size {
    height: 1.5rem;
    padding-left: 0.75rem;
    padding-right: 0.75rem;
    font-size: 0.875rem;
    border-radius: 0.75rem;
  }

  .large-size {
    height: 3rem;
    font-size: 1.5rem;
    padding-left: 2rem;
    padding-right: 2rem;
    border-radius: 1.5rem;
  }
</style>

<script lang="ts">
  import { goto } from '@sapper/app';
  import { tick } from 'svelte';

  import { buttonColorMap } from '../../lib/style/palette';

  export let to = '';
  export let size: ButtonSize = 'DEFAULT';
  export let color: Color = 'teal';
  export let border = false;
  export let inline = false;

  let ref: HTMLButtonElement;

  const buttonColor = buttonColorMap[color];

  const navigateToPage = async () => {
    await goto(to);
  };

  type ButtonSize = 'SMALL' | 'DEFAULT' | 'LARGE';
  type Color = 'teal' | 'gray' | 'darkGray' | 'lightGray';

  $: {
    if (ref && border) {
      (async function () {
        ref.style.border = `1px solid ${buttonColor.background}`;
        ref.style.color = buttonColor.background;
        await tick();
      })();
    }
  }
</script>

<!-- markup (zero or more items) goes here -->
{#if to}
  <button
    class="round-btn"
    type="button"
    bind:this="{ref}"
    on:click|preventDefault="{navigateToPage}"
    class:inline-btn="{inline}"
    class:border-btn="{border}"
    class:default-size="{size === 'DEFAULT'}"
    class:small-size="{size === 'SMALL'}"
    class:large-size="{size === 'LARGE'}"
  >
    <slot>
      <!-- optiinal fallback -->
    </slot>
  </button>
{:else}
  <button
    on:click
    on:submit
    bind:this="{ref}"
    class="round-btn"
    class:inline-btn="{inline}"
    class:border-btn="{border}"
    class:default-size="{size === 'DEFAULT'}"
    class:small-size="{size === 'SMALL'}"
    class:large-size="{size === 'LARGE'}"
  >
    <slot>
      <!-- optiinal fallback -->
    </slot>
  </button>
{/if}
